name: Build and Deploy
on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.14.0

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.x'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

#      - uses: actions/upload-artifact@v3
#        with:
#          name: dist
#          path: dist

      - run: zip -r build.zip dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build.zip"
