name: Rollback
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Release Version"
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Download Artifact
        uses: robinraju/release-downloader@v1.9
        with:
          tag: ${{ github.event.inputs.name }}
          fileName: build.zip
          extract: true

      - name: Deploy
        run: |
          cat dist/index.html
