name: Rollback
on: workflow_dispatch

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Download Artifact
        uses: robinraju/release-downloader@v1.9
        with:
          tag: ${{ steps.vars.outputs.short_ref }}
          fileName: build.zip
          extract: true

      - name: Deploy
        run: |
          cat dist/index.html
